import{a as L,S as v,i as a}from"./assets/vendor-YT4DRQk6.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const S="48709944-704d63a27b5727393d509020c",q="https://pixabay.com/api/";async function m(o,t,i){const s=`${q}?key=${S}&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${i}`;return(await L.get(s)).data}function h(o){const t=document.querySelector(".gallery"),i=o.map(({webformatURL:s,largeImageURL:e,tags:r,likes:n,views:g,comments:y,downloads:b})=>`
          <a href="${e}" class="gallery-item">
            <img src="${s}" alt="${r}" loading="lazy" />
            <div class="info">
              <p><b>❤️ Likes:</b> ${n}</p>
              <p><b>👁 Views:</b> ${g}</p>
              <p><b>💬 Comments:</b> ${y}</p>
              <p><b>📥 Downloads:</b> ${b}</p>
            </div>
          </a>`).join("");t.insertAdjacentHTML("beforeend",i)}function w(){document.querySelector(".gallery").innerHTML=""}const $=document.querySelector("#search-form");document.querySelector(".gallery");const d=document.querySelector(".load-more"),u=document.querySelector(".loader");let l="",c=1;const p=40;let f=new v(".gallery a");$.addEventListener("submit",async o=>{if(o.preventDefault(),l=o.currentTarget.elements.searchQuery.value.trim(),!l){a.error({title:"Error",message:"Type the request !",position:"topRight"});return}c=1,w(),d.classList.add("hidden"),u.classList.remove("hidden");try{const t=await m(l,c,p);if(t.hits.length===0){a.warning({title:"❌ Attention",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(t.hits),f.refresh(),t.totalHits>p&&d.classList.remove("hidden")}catch{a.error({title:"❌ Error",message:"Can not load the images!",position:"topRight"})}finally{u.classList.add("hidden")}});d.addEventListener("click",async()=>{c+=1,u.classList.remove("hidden");try{const o=await m(l,c,p);h(o.hits),f.refresh();const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),c*p>=o.totalHits&&(d.classList.add("hidden"),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{a.error({title:"Error",message:"Something went wrong.",position:"topRight"})}finally{u.classList.add("hidden")}});
//# sourceMappingURL=index.js.map
